POST http://localhost:8080/person
Content-Type: application/json

{
  "id": "ieiiieiie",
  "name": "ie",
  "age": "12",
  "birthDate": "20020301",
  "phone": "010-2329-9421"
}

###

GET http://localhost:8080/person/ieiiieiie

###

DELETE http://localhost:8080/person/ieiiieiie

###